apiVersion: operator.yugabyte.io/v1alpha1
kind: Release
metadata:
  name: "2.19.3.0-b140"  
spec:
  config:
    version: "2.19.3.0-b140"
    downloadConfig:
      http:
        paths:
          helmChart: "https://charts.yugabyte.com/yugabyte-2.19.3.tgz" 
          x86_64: "https://downloads.yugabyte.com/releases/2.19.3.0/yugabyte-2.19.3.0-b140-linux-x86_64.tar.gz" 

---
apiVersion: operator.yugabyte.io/v1alpha1
kind: Release
metadata:
  name: "2.20.1.3-b3"
spec:
  config:
    version: "2.20.1.3-b3"
    downloadConfig:
      http:
        paths:
          helmChart: "https://charts.yugabyte.com/yugabyte-2.20.1.tgz" 
          x86_64: "https://downloads.yugabyte.com/releases/2.20.1.3/yugabyte-2.20.1.3-b3-linux-x86_64.tar.gz"
---
apiVersion: operator.yugabyte.io/v1alpha1
kind: Release
metadata:
  name: "2.20.5.0-b72"
spec:
  config:
    version: "2.20.5.0-b72"
    downloadConfig:
      http:
        paths:
          helmChart: "https://charts.yugabyte.com/yugabyte-2.20.5.tgz" 
          x86_64: "https://downloads.yugabyte.com/releases/2.20.5.0/yugabyte-2.20.5.0-b72-linux-x86_64.tar.gz"
---
apiVersion: operator.yugabyte.io/v1alpha1
kind: Release
metadata:
  name:  "2.18.6.0-b73"
spec:
  config:
    version: "2.18.6.0-b73" 
    downloadConfig:
      http:
        paths:
          helmChart: "https://charts.yugabyte.com/yugabyte-2.18.6.tgz" 
          x86_64: "https://downloads.yugabyte.com/releases/2.18.6.0/yugabyte-2.18.6.0-b73-linux-x86_64.tar.gz"

---
apiVersion: operator.yugabyte.io/v1alpha1
kind: Release
metadata:
  name: "2024.1.1.0-b137"
spec:
  config:
    version: "2024.1.1.0-b137"
    downloadConfig:
      http:
        paths:
          helmChart: "https://charts.yugabyte.com/yugabyte-2024.1.1.tgz" 
          x86_64: "https://downloads.yugabyte.com/releases/2024.1.0.0/yugabyte-2024.1.0.0-b129-linux-x86_64.tar.gz"
---          
apiVersion: operator.yugabyte.io/v1alpha1
kind: Release
metadata:
  name: "2.21.1.0-b271"
spec:
  config:
    version: "2.21.1.0-b271"
    downloadConfig:
      http:
        paths:
          helmChart: "https://charts.yugabyte.com/yugabyte-2.21.1.tgz" 
          x86_64: "https://downloads.yugabyte.com/releases/2.21.1.0/yugabyte-2.21.1.0-b271-linux-x86_64.tar.gz"
---
apiVersion: operator.yugabyte.io/v1alpha1
kind: Release
metadata:
  name: "2.21.0.1-b1"
spec:
  config:
    version: "2.21.0.1-b1"
    downloadConfig:
      http:
        paths:
          helmChart: "https://charts.yugabyte.com/yugabyte-2.21.0.tgz" 
          x86_64: "https://downloads.yugabyte.com/releases/2.21.0.1/yugabyte-2.21.0.1-b1-linux-x86_64.tar.gz"
---
apiVersion: operator.yugabyte.io/v1alpha1
kind: Release
metadata:
  name: "2024.2.0.0-b145"
spec:
  config:
    version: "2024.2.0.0-b145"
    downloadConfig:
      http:
        paths:
          helmChart: "https://charts.yugabyte.com/yugabyte-2024.2.0.tgz" 
          x86_64: "https://downloads.yugabyte.com/releases/2024.2.0.0/yugabyte-2024.2.0.0-b145-darwin-x86_64.tar.gz"
---
